apiVersion: v1
kind: Service
metadata:
  name: webblog-api
spec:
  selector:
    app: webblog-service
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      nodePort: 32767 # Port to be exposed internally to other nodes.
      tcp:
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
